/* Main.ino file generated by New Project wizard
 *
 * Created:   Mon Apr 15 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")


#pragma GCC pop_options

const int led1 = 4; //green LED
const int led2 = 5;  //REd LED
const int echoPin = 2; 
const int pingPin = 3;
const int buzzerPin = 6; // Buzzer pin
const int nThreshold = 300;  //30 cm threshold
long nDuration;
long nDistance;



void setup()
{
  pinMode(led1, OUTPUT);
  pinMode(led2, OUTPUT);
  pinMode(pingPin, OUTPUT);
  pinMode(echoPin, INPUT);
  pinMode(buzzerPin, OUTPUT);
  Serial.begin(9600);
  Serial.println("Starting ultrasonic detector...");
}
void loop() {
  digitalWrite(pingPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(pingPin, LOW);
  nDuration = pulseIn(echoPin, HIGH);
  nDistance= microsecondsToCentimeters(nDuration);
  Serial.print(nDistance);
  Serial.println(" cm");
  if(nDistance < nThreshold) {
    tone(buzzerPin, 2000);
    digitalWrite(led2, HIGH);
    delay(400);
	tone(buzzerPin,2000);
    delay(300);
	noTone(buzzerPin);
    digitalWrite(led2, LOW);
  }
  else{
    digitalWrite(led1, HIGH);
    delay(400);
    digitalWrite(led1, LOW);
  }
}

long microsecondsToCentimeters(long microseconds) // method to covert microsec to centimeters
{
   return microseconds / 29 / 2;
   }